# Permalinks
permalink:        pretty

# Setup
title:            tfcb.fredhutch.io
tagline:          'Education and access to computational methods at the <a href="http://fredhutch.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
description:      'Education and access to computational methods at the <a href="http://fredhutch.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
url:              http://tfcb.fredhutch.io
timezone:         America/Los_Angeles
future:           True

# Custom vars

github:
  repo:           https://github.com/fredhutchio/fredhutch.io

trello:           https://trello.com/b/IwMlMEWl/fhcrc-io
